name: sovrin-build
# TODO: Set apropriate triggers
on: [ pull_request, workflow_dispatch]

jobs:
#   workflow-setup:
#     runs-on: ubuntu-latest
#     outputs:
#       CACHE_KEY_LINT: ${{ steps.cache.outputs.CACHE_KEY_LINT }}
#       # Expose the lowercase version of the GitHub repository name
#       # to all subsequent jobs that reference image repositories
#       # as the push and pull operations require the URL of the repository 
#       # to be in lowercase.
#       GITHUB_REPOSITORY_NAME: ${{ steps.cache.outputs.GITHUB_REPOSITORY_NAME }}
#     steps:
#       - name: Git checkout
#         uses: actions/checkout@v2
#       - name: Set outputs
#         id: cache
#         run: |
#           echo "::set-output name=CACHE_KEY_LINT::${{ hashFiles('.github/workflows/lint/Dockerfile') }}"
#           echo "::set-output name=GITHUB_REPOSITORY_NAME::$(echo ${GITHUB_REPOSITORY,,})"

#   build-lint-image:
#     needs: workflow-setup
#     runs-on: ubuntu-latest
#     env:
#       DOCKER_BUILDKIT: 1
#       CACHE_KEY_LINT: ${{ needs.workflow-setup.outputs.CACHE_KEY_LINT }}
#       GITHUB_REPOSITORY_NAME: ${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
#     steps:
#       - name: Git checkout
#         uses: actions/checkout@v2
#       - name: Try load from cache.
#         id: cache-image-lint
#         uses: actions/cache@v2
#         with:
#           path: ${GITHUB_WORKSPACE}/cache
#           key: ${{ env.CACHE_KEY_LINT }}
#       - name: If NOT found in cache, build and push image.
#         if: steps.cache-image-lint.outputs.cache-hit != 'true'
#         run: |
#           echo ${{ secrets.CR_PAT }} | docker login ghcr.io --username ${{ secrets.CR_USER }} --password-stdin
#           docker build -f .github/workflows/lint/Dockerfile --no-cache -t ${{ env.GITHUB_REPOSITORY_NAME }}/indy-node-lint:${{ env.CACHE_KEY_LINT }} .
#           docker tag ${{ env.GITHUB_REPOSITORY_NAME }}/indy-node-lint:${{ env.CACHE_KEY_LINT }} ghcr.io/${{ env.GITHUB_REPOSITORY_NAME }}/indy-node-lint:latest
#           docker push ghcr.io/${{ env.GITHUB_REPOSITORY_NAME }}/indy-node-lint:latest
#           mkdir -p ${GITHUB_WORKSPACE}/cache
#           touch ${GITHUB_WORKSPACE}/cache/${{ env.CACHE_KEY_LINT }}
#   lint:
#     name: lint
#     runs-on: ubuntu-latest
#     container:
#       image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/indy-node-lint
#     needs: [workflow-setup, build-lint-image]
#     steps:      
#       - name: Check out code
#         uses: actions/checkout@v2
#       - name: flake8
#         run: python3 -m flake8

  buld-package:
    name: build-package
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build package
        run: |
          cd build-scripts/ubuntu-1604
          ./build-sovrin-docker.sh "${PWD}/../.." 1.0.0
          ls sovrin-deb-u1604
